[package]
name = "lucidmq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lucidmq"
path = "src/lib.rs"

[[bin]]
name = "lucidmq_bin"
path = "src/main.rs"

[dependencies]
nolan = { path = "../nolan" }
bincode="1.3.3"
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.9.0"
rand = "0.8.5"
